### ISSUE TITLE
make -j launches too many jobs

### ISSUE THREAD

**Issue by fauno** [ankane/cmdstan-ruby#2]
Hi! I was enabling prophet support to blazer and had to compile this gem, but the `make -j` launches a lot of concurrent jobs and it nearly crashed my dev machine.  Would you accept a patch that removes it or maybe adds an env variable to set the amount of jobs?

**Comment by ankane** [comment]
Hey @fauno, thanks for the suggestion. Agree it should be a better citizen. Removed the `-j` flag and will push out a new release shortly.
